//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WApiInmoviliaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Tel
    {
        public int id_tipo_tel { get; set; }
        public string descripcion { get; set; }
    }
}
